/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste;

/**
 *
 * @author guscc
 */
public class VisualTest extends javax.swing.JFrame {

    /**
     * Creates new form VisualTest
     */
    public VisualTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jan_25 = new javax.swing.JButton();
        jan_19 = new javax.swing.JButton();
        jan_20 = new javax.swing.JButton();
        jan_21 = new javax.swing.JButton();
        jan_22 = new javax.swing.JButton();
        jan_23 = new javax.swing.JButton();
        jan_24 = new javax.swing.JButton();
        jan_12 = new javax.swing.JButton();
        jan_13 = new javax.swing.JButton();
        jan_14 = new javax.swing.JButton();
        jan_15 = new javax.swing.JButton();
        jan_16 = new javax.swing.JButton();
        jan_17 = new javax.swing.JButton();
        jan_18 = new javax.swing.JButton();
        jan_5 = new javax.swing.JButton();
        jan_6 = new javax.swing.JButton();
        jan_7 = new javax.swing.JButton();
        jan_8 = new javax.swing.JButton();
        jan_9 = new javax.swing.JButton();
        jan_10 = new javax.swing.JButton();
        jan_11 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jan_1 = new javax.swing.JButton();
        jan_2 = new javax.swing.JButton();
        jan_3 = new javax.swing.JButton();
        jan_4 = new javax.swing.JButton();
        jan_26 = new javax.swing.JButton();
        jan_27 = new javax.swing.JButton();
        jan_28 = new javax.swing.JButton();
        jan_29 = new javax.swing.JButton();
        jan_30 = new javax.swing.JButton();
        jan_31 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto_1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(100, 150, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(200, 240, 240));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Janeiro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 450, 50));

        jan_25.setText("25");
        jan_25.setToolTipText("");
        jan_25.setBorderPainted(false);
        jan_25.setFocusPainted(false);
        jan_25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_25.setOpaque(false);
        jan_25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 150, 150));

        jan_19.setText("19");
        jan_19.setToolTipText("");
        jan_19.setBorderPainted(false);
        jan_19.setFocusPainted(false);
        jan_19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_19.setOpaque(false);
        jan_19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 150, 150));

        jan_20.setText("20");
        jan_20.setToolTipText("");
        jan_20.setBorderPainted(false);
        jan_20.setFocusPainted(false);
        jan_20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_20.setOpaque(false);
        jan_20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 150, 150));

        jan_21.setText("21");
        jan_21.setToolTipText("");
        jan_21.setBorderPainted(false);
        jan_21.setFocusPainted(false);
        jan_21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_21.setOpaque(false);
        jan_21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 150, 150));

        jan_22.setText("22");
        jan_22.setToolTipText("");
        jan_22.setBorderPainted(false);
        jan_22.setFocusPainted(false);
        jan_22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_22.setOpaque(false);
        jan_22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 150, 150));

        jan_23.setText("23");
        jan_23.setToolTipText("");
        jan_23.setBorderPainted(false);
        jan_23.setFocusPainted(false);
        jan_23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_23.setOpaque(false);
        jan_23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 150, 150));

        jan_24.setText("24");
        jan_24.setToolTipText("");
        jan_24.setBorderPainted(false);
        jan_24.setFocusPainted(false);
        jan_24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_24.setOpaque(false);
        jan_24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 150, 150));

        jan_12.setText("12");
        jan_12.setToolTipText("");
        jan_12.setBorderPainted(false);
        jan_12.setFocusPainted(false);
        jan_12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_12.setOpaque(false);
        jan_12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 150, 150));

        jan_13.setText("13");
        jan_13.setToolTipText("");
        jan_13.setBorderPainted(false);
        jan_13.setFocusPainted(false);
        jan_13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_13.setOpaque(false);
        jan_13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_13ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 150, 150));

        jan_14.setText("14");
        jan_14.setToolTipText("");
        jan_14.setBorderPainted(false);
        jan_14.setFocusPainted(false);
        jan_14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_14.setOpaque(false);
        jan_14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 150, 150));

        jan_15.setText("15");
        jan_15.setToolTipText("");
        jan_15.setBorderPainted(false);
        jan_15.setFocusPainted(false);
        jan_15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_15.setOpaque(false);
        jan_15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 150, 150));

        jan_16.setText("16");
        jan_16.setToolTipText("");
        jan_16.setBorderPainted(false);
        jan_16.setFocusPainted(false);
        jan_16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_16.setOpaque(false);
        jan_16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 150, 150));

        jan_17.setText("17");
        jan_17.setToolTipText("");
        jan_17.setBorderPainted(false);
        jan_17.setFocusPainted(false);
        jan_17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_17.setOpaque(false);
        jan_17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_17ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 150, 150));

        jan_18.setText("18");
        jan_18.setToolTipText("");
        jan_18.setBorderPainted(false);
        jan_18.setFocusPainted(false);
        jan_18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_18.setOpaque(false);
        jan_18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, 150, 150));

        jan_5.setText("5");
        jan_5.setToolTipText("");
        jan_5.setBorderPainted(false);
        jan_5.setFocusPainted(false);
        jan_5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_5.setOpaque(false);
        jan_5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 150, 150));

        jan_6.setText("6");
        jan_6.setToolTipText("");
        jan_6.setBorderPainted(false);
        jan_6.setFocusPainted(false);
        jan_6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_6.setOpaque(false);
        jan_6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_6ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, 150));

        jan_7.setText("7");
        jan_7.setToolTipText("");
        jan_7.setBorderPainted(false);
        jan_7.setFocusPainted(false);
        jan_7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_7.setOpaque(false);
        jan_7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_7ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 150, 150));

        jan_8.setText("8");
        jan_8.setToolTipText("");
        jan_8.setBorderPainted(false);
        jan_8.setFocusPainted(false);
        jan_8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_8.setOpaque(false);
        jan_8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 150, 150));

        jan_9.setText("9");
        jan_9.setToolTipText("");
        jan_9.setBorderPainted(false);
        jan_9.setFocusPainted(false);
        jan_9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_9.setOpaque(false);
        jan_9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 150, 150));

        jan_10.setText("10");
        jan_10.setToolTipText("");
        jan_10.setBorderPainted(false);
        jan_10.setFocusPainted(false);
        jan_10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_10.setOpaque(false);
        jan_10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_10ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 150, 150));

        jan_11.setText("11");
        jan_11.setToolTipText("");
        jan_11.setBorderPainted(false);
        jan_11.setFocusPainted(false);
        jan_11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_11.setOpaque(false);
        jan_11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 150, 150));

        jButton22.setToolTipText("");
        jButton22.setBorderPainted(false);
        jButton22.setFocusPainted(false);
        jButton22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton22.setOpaque(false);
        jButton22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 150));

        jButton23.setToolTipText("");
        jButton23.setBorderPainted(false);
        jButton23.setFocusPainted(false);
        jButton23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setOpaque(false);
        jButton23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 150));

        jButton24.setToolTipText("");
        jButton24.setBorderPainted(false);
        jButton24.setFocusPainted(false);
        jButton24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setOpaque(false);
        jButton24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 150, 150));

        jan_1.setText("1");
        jan_1.setToolTipText("");
        jan_1.setBorderPainted(false);
        jan_1.setFocusPainted(false);
        jan_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_1.setNextFocusableComponent(jan_1);
        jan_1.setOpaque(false);
        jan_1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_1ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 150, 150));

        jan_2.setText("2");
        jan_2.setToolTipText("");
        jan_2.setBorderPainted(false);
        jan_2.setFocusPainted(false);
        jan_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_2.setOpaque(false);
        jan_2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_2ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 150, 150));

        jan_3.setText("3");
        jan_3.setToolTipText("");
        jan_3.setBorderPainted(false);
        jan_3.setFocusPainted(false);
        jan_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_3.setOpaque(false);
        jan_3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_3ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 150, 150));

        jan_4.setText("4");
        jan_4.setToolTipText("abc");
        jan_4.setBorderPainted(false);
        jan_4.setFocusPainted(false);
        jan_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_4.setOpaque(false);
        jan_4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 150, 150));

        jan_26.setText("26");
        jan_26.setToolTipText("");
        jan_26.setBorderPainted(false);
        jan_26.setFocusPainted(false);
        jan_26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_26.setOpaque(false);
        jan_26.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 150, 150));

        jan_27.setText("27");
        jan_27.setToolTipText("");
        jan_27.setBorderPainted(false);
        jan_27.setFocusPainted(false);
        jan_27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_27.setOpaque(false);
        jan_27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, 150, 150));

        jan_28.setText("28");
        jan_28.setToolTipText("");
        jan_28.setBorderPainted(false);
        jan_28.setFocusPainted(false);
        jan_28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_28.setOpaque(false);
        jan_28.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, 150, 150));

        jan_29.setText("29");
        jan_29.setToolTipText("");
        jan_29.setBorderPainted(false);
        jan_29.setFocusPainted(false);
        jan_29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_29.setOpaque(false);
        jan_29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, 150, 150));

        jan_30.setText("30");
        jan_30.setToolTipText("");
        jan_30.setBorderPainted(false);
        jan_30.setFocusPainted(false);
        jan_30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_30.setOpaque(false);
        jan_30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jan_30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jan_30ActionPerformed(evt);
            }
        });
        jPanel1.add(jan_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 670, 150, 150));

        jan_31.setText("31");
        jan_31.setToolTipText("");
        jan_31.setBorderPainted(false);
        jan_31.setFocusPainted(false);
        jan_31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jan_31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jan_31.setOpaque(false);
        jan_31.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jan_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 670, 150, 150));

        jButton35.setToolTipText("");
        jButton35.setBorderPainted(false);
        jButton35.setFocusPainted(false);
        jButton35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setOpaque(false);
        jButton35.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, 150, 150));

        jScrollBar1.setBackground(new java.awt.Color(100, 200, 200));
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });
        jPanel1.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        texto_1.setColumns(20);
        texto_1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        texto_1.setRows(5);
        texto_1.setText(" 1\n\n12:00 - Aniversário");
        texto_1.setBorder(null);
        texto_1.setMinimumSize(new java.awt.Dimension(100, 100));
        texto_1.setName(""); // NOI18N
        texto_1.setPreferredSize(new java.awt.Dimension(150, 150));
        texto_1.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(texto_1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 150, 150));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("2\n\n12:00 - Aniversário");
        jTextArea4.setBorder(null);
        jTextArea4.setMinimumSize(new java.awt.Dimension(100, 100));
        jTextArea4.setName(""); // NOI18N
        jTextArea4.setPreferredSize(new java.awt.Dimension(150, 150));
        jTextArea4.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 150, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("3\n\n12:00 - Aniversário");
        jTextArea2.setBorder(null);
        jTextArea2.setMinimumSize(new java.awt.Dimension(100, 100));
        jTextArea2.setName(""); // NOI18N
        jTextArea2.setPreferredSize(new java.awt.Dimension(150, 150));
        jTextArea2.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 430, 150, 150));

        jPanel2.setBackground(new java.awt.Color(20, 22, 200));
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel2KeyReleased(evt);
            }
        });
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 160, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jan_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_10ActionPerformed

    private void jan_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_13ActionPerformed

    private void jan_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_17ActionPerformed

    private void jan_30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_30ActionPerformed

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    private void jPanel2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2KeyReleased

    private void jan_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_7ActionPerformed

    private void jan_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_6ActionPerformed

    private void jan_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_3ActionPerformed

    private void jan_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jan_2ActionPerformed

    private void jan_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jan_1ActionPerformed
        System.out.println("Pega no meu pé");
        VisualTest vt = new VisualTest();
        vt.setVisible(true);
    }//GEN-LAST:event_jan_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton35;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JButton jan_1;
    private javax.swing.JButton jan_10;
    private javax.swing.JButton jan_11;
    private javax.swing.JButton jan_12;
    private javax.swing.JButton jan_13;
    private javax.swing.JButton jan_14;
    private javax.swing.JButton jan_15;
    private javax.swing.JButton jan_16;
    private javax.swing.JButton jan_17;
    private javax.swing.JButton jan_18;
    private javax.swing.JButton jan_19;
    private javax.swing.JButton jan_2;
    private javax.swing.JButton jan_20;
    private javax.swing.JButton jan_21;
    private javax.swing.JButton jan_22;
    private javax.swing.JButton jan_23;
    private javax.swing.JButton jan_24;
    private javax.swing.JButton jan_25;
    private javax.swing.JButton jan_26;
    private javax.swing.JButton jan_27;
    private javax.swing.JButton jan_28;
    private javax.swing.JButton jan_29;
    private javax.swing.JButton jan_3;
    private javax.swing.JButton jan_30;
    private javax.swing.JButton jan_31;
    private javax.swing.JButton jan_4;
    private javax.swing.JButton jan_5;
    private javax.swing.JButton jan_6;
    private javax.swing.JButton jan_7;
    private javax.swing.JButton jan_8;
    private javax.swing.JButton jan_9;
    private javax.swing.JTextArea texto_1;
    // End of variables declaration//GEN-END:variables
}
