/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AdicionarEvento extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarEvento
     */
    public AdicionarEvento() {
        initComponents();
    }
private void salvar(){
        String url = "jdbc:mysql://localhost/gato?useSSL=false", usuario = "root", senha = "root";
        Connection conexao;
        PreparedStatement pstm;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdicionarEventoSemanal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String titulo, horaIni, horaFin, minIni, minFin, descricao, ano, mes, dia;
        int favorito, escolar, feriado;
        titulo = jTextField1.getText();
        descricao = jTextField2.getText();
        ano = BoxAnoData.getSelectedItem().toString();
        mes = BoxMesData.getSelectedItem().toString();
        dia = BoxDiaData.getSelectedItem().toString();
        horaIni = BoxHoraInicio.getSelectedItem().toString();
        minIni = BoxMinInicio.getSelectedItem().toString();
        horaFin = BoxHoraFim.getSelectedItem().toString();
        minFin = BoxMinFim.getSelectedItem().toString();
        if (BotaoBooleanoFavoito.isSelected())
            favorito = 1;
        else
            favorito = 0;
        
        if (BotaoBooleanoEscolar.isSelected())
            escolar = 1;
        else
            escolar = 0;
        
        if (BotaoBooleanoFeriado.isSelected())
            feriado = 1;
        else
            feriado = 0;
        
        try {
            conexao = DriverManager.getConnection(url, usuario, senha);
            pstm = conexao.prepareStatement("insert into Evento values (null, ?, ?, ?, ?, ?, ?, ?, ?)");

            pstm.setString(1, titulo);
            pstm.setString(2, ano +"-"+ mes +"-"+ dia);
            pstm.setString(3, horaIni +":"+ minIni);
            pstm.setString(4, horaFin +":"+ minFin);
            pstm.setString(5, descricao);
            pstm.setInt(6, escolar);
            pstm.setInt(7, feriado);
            pstm.setInt(8, favorito);
            
            pstm.execute();
            pstm.close();
            conexao.close();
            
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        } catch (HeadlessException | SQLException excp) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar.");
            System.err.println(excp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        BotaoAvancar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        LabelTitulo = new javax.swing.JLabel();
        LabelDescricao = new javax.swing.JLabel();
        BoxAnoData = new javax.swing.JComboBox<>();
        BoxHoraInicio = new javax.swing.JComboBox<>();
        BoxHoraFim = new javax.swing.JComboBox<>();
        LabelData = new javax.swing.JLabel();
        LabelHorarioDeInicio = new javax.swing.JLabel();
        LabelHorarioDeFim = new javax.swing.JLabel();
        BoxMinInicio = new javax.swing.JComboBox<>();
        BoxMinFim = new javax.swing.JComboBox<>();
        Label2PontosHI = new javax.swing.JLabel();
        Label2PontosHF = new javax.swing.JLabel();
        BoxMesData = new javax.swing.JComboBox<>();
        BoxDiaData = new javax.swing.JComboBox<>();
        LabelMarcarEvento = new javax.swing.JLabel();
        BotaoBooleanoFavoito = new javax.swing.JRadioButton();
        BotaoBooleanoEscolar = new javax.swing.JRadioButton();
        BotaoBooleanoFeriado = new javax.swing.JRadioButton();
        LabelBarraData1 = new javax.swing.JLabel();
        LabelBarraData2 = new javax.swing.JLabel();

        jButton1.setText("avançar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Evento");
        setPreferredSize(new java.awt.Dimension(640, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoAvancar.setText("Avançar");
        BotaoAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 321, -1, -1));

        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 321, -1, -1));

        jTextField1.setToolTipText("informe o nome do evento");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 35, 567, 27));

        jTextField2.setToolTipText("informe algo sobre esse evento");
        jTextField2.setPreferredSize(new java.awt.Dimension(79, 20));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 89, 567, 27));

        LabelTitulo.setText("Título");
        getContentPane().add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 15, -1, -1));

        LabelDescricao.setText("Descrição");
        getContentPane().add(LabelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 68, -1, 15));

        BoxAnoData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        BoxAnoData.setPreferredSize(new java.awt.Dimension(57, 29));
        BoxAnoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxAnoDataActionPerformed(evt);
            }
        });
        getContentPane().add(BoxAnoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 70, 23));

        BoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        BoxHoraInicio.setPreferredSize(new java.awt.Dimension(57, 29));
        getContentPane().add(BoxHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 231, 57, 23));

        BoxHoraFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        getContentPane().add(BoxHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 311, 57, 22));

        LabelData.setText("Data");
        getContentPane().add(LabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 134, -1, -1));

        LabelHorarioDeInicio.setText("Horário de inicio");
        getContentPane().add(LabelHorarioDeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 202, -1, -1));

        LabelHorarioDeFim.setText("Horário de fim");
        getContentPane().add(LabelHorarioDeFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 286, -1, -1));

        BoxMinInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));
        getContentPane().add(BoxMinInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 231, 57, 23));

        BoxMinFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));
        getContentPane().add(BoxMinFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 311, 57, 22));

        Label2PontosHI.setText(":");
        getContentPane().add(Label2PontosHI, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 237, -1, -1));

        Label2PontosHF.setText(":");
        getContentPane().add(Label2PontosHF, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 311, 10, -1));

        BoxMesData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(BoxMesData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 57, 23));

        BoxDiaData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        BoxDiaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDiaDataActionPerformed(evt);
            }
        });
        getContentPane().add(BoxDiaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 57, 23));

        LabelMarcarEvento.setText("Marcar Evento como : ");
        getContentPane().add(LabelMarcarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 134, -1, -1));

        BotaoBooleanoFavoito.setText("Favorito");
        getContentPane().add(BotaoBooleanoFavoito, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 161, -1, -1));

        BotaoBooleanoEscolar.setText("Escolar");
        getContentPane().add(BotaoBooleanoEscolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 201, -1, -1));

        BotaoBooleanoFeriado.setText("Feriado");
        getContentPane().add(BotaoBooleanoFeriado, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 241, -1, -1));

        LabelBarraData1.setText("/");
        getContentPane().add(LabelBarraData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 165, -1, -1));

        LabelBarraData2.setText("/");
        getContentPane().add(LabelBarraData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 165, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    /** 
     * Fechar apenas a janela atual
     */
    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        AdicionarEvento.this.dispose(); 
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void BoxDiaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxDiaDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxDiaDataActionPerformed

    private void BoxAnoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxAnoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxAnoDataActionPerformed
    
    /** 
     * Gatilho do botão Avançar para chamar a função salvar()
     */
    private void BotaoAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAvancarActionPerformed
       salvar();
    }//GEN-LAST:event_BotaoAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAvancar;
    private javax.swing.JRadioButton BotaoBooleanoEscolar;
    private javax.swing.JRadioButton BotaoBooleanoFavoito;
    private javax.swing.JRadioButton BotaoBooleanoFeriado;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JComboBox<String> BoxAnoData;
    private javax.swing.JComboBox<String> BoxDiaData;
    private javax.swing.JComboBox<String> BoxHoraFim;
    private javax.swing.JComboBox<String> BoxHoraInicio;
    private javax.swing.JComboBox<String> BoxMesData;
    private javax.swing.JComboBox<String> BoxMinFim;
    private javax.swing.JComboBox<String> BoxMinInicio;
    private javax.swing.JLabel Label2PontosHF;
    private javax.swing.JLabel Label2PontosHI;
    private javax.swing.JLabel LabelBarraData1;
    private javax.swing.JLabel LabelBarraData2;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JLabel LabelHorarioDeFim;
    private javax.swing.JLabel LabelHorarioDeInicio;
    private javax.swing.JLabel LabelMarcarEvento;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
