/*
 * Copyright (C) 2019 guscc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gato;

/**
 *
 * @author guscc
 */
public class CalendarioRotinaNew extends javax.swing.JFrame {

    /**
     * Creates new form CalendarioRotinaNew
     */
    public CalendarioRotinaNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotinaScroll = new javax.swing.JScrollPane();
        rotinaPanel = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        diasSemana = new javax.swing.JPanel();
        horariosTitulo = new javax.swing.JLabel();
        domingoTitulo = new javax.swing.JLabel();
        segundaTitulo = new javax.swing.JLabel();
        tercaTitulo = new javax.swing.JLabel();
        quartaTitulo = new javax.swing.JLabel();
        quintaTitulo = new javax.swing.JLabel();
        sextaTitulo = new javax.swing.JLabel();
        sabadoTitulo = new javax.swing.JLabel();
        diasSemana1 = new javax.swing.JPanel();
        horariosPanel = new javax.swing.JPanel();
        time0 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        time6 = new javax.swing.JLabel();
        time7 = new javax.swing.JLabel();
        time8 = new javax.swing.JLabel();
        time9 = new javax.swing.JLabel();
        time10 = new javax.swing.JLabel();
        time11 = new javax.swing.JLabel();
        time12 = new javax.swing.JLabel();
        time13 = new javax.swing.JLabel();
        time14 = new javax.swing.JLabel();
        time15 = new javax.swing.JLabel();
        time16 = new javax.swing.JLabel();
        time17 = new javax.swing.JLabel();
        time18 = new javax.swing.JLabel();
        time19 = new javax.swing.JLabel();
        time20 = new javax.swing.JLabel();
        time21 = new javax.swing.JLabel();
        time22 = new javax.swing.JLabel();
        time23 = new javax.swing.JLabel();
        time24 = new javax.swing.JLabel();
        domingoPanel = new javax.swing.JPanel();
        segundaPanel = new javax.swing.JPanel();
        tercaPanel = new javax.swing.JPanel();
        quartaPanel = new javax.swing.JPanel();
        quintaPanel = new javax.swing.JPanel();
        sextaPanel = new javax.swing.JPanel();
        sabadoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotinaPanel.setMinimumSize(new java.awt.Dimension(100, 674));
        rotinaPanel.setPreferredSize(new java.awt.Dimension(100, 674));
        rotinaPanel.setLayout(new java.awt.BorderLayout());

        tituloPanel.setMinimumSize(new java.awt.Dimension(892, 746));
        tituloPanel.setLayout(new java.awt.BorderLayout());

        tituloLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Calendário de Rotina");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloPanel.add(tituloLabel, java.awt.BorderLayout.NORTH);

        diasSemana.setLayout(new java.awt.GridLayout());

        horariosTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        horariosTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horariosTitulo.setText("Horários");
        diasSemana.add(horariosTitulo);

        domingoTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        domingoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        domingoTitulo.setText("Domingo");
        diasSemana.add(domingoTitulo);

        segundaTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        segundaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segundaTitulo.setText("Segunda");
        diasSemana.add(segundaTitulo);

        tercaTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tercaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tercaTitulo.setText("Terça");
        diasSemana.add(tercaTitulo);

        quartaTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        quartaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quartaTitulo.setText("Quarta");
        diasSemana.add(quartaTitulo);

        quintaTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        quintaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quintaTitulo.setText("Quinta");
        diasSemana.add(quintaTitulo);

        sextaTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sextaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sextaTitulo.setText("Sexta");
        diasSemana.add(sextaTitulo);

        sabadoTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sabadoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sabadoTitulo.setText("Sábado");
        diasSemana.add(sabadoTitulo);

        tituloPanel.add(diasSemana, java.awt.BorderLayout.CENTER);

        rotinaPanel.add(tituloPanel, java.awt.BorderLayout.NORTH);

        diasSemana1.setLayout(new java.awt.GridLayout());

        horariosPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        horariosPanel.setLayout(new javax.swing.BoxLayout(horariosPanel, javax.swing.BoxLayout.PAGE_AXIS));

        time0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time0.setText("00:00");
        time0.setAlignmentX(0.5F);
        horariosPanel.add(time0);

        time1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time1.setText("01:00");
        time1.setAlignmentX(0.5F);
        horariosPanel.add(time1);

        time2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time2.setText("02:00");
        time2.setAlignmentX(0.5F);
        horariosPanel.add(time2);

        time3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time3.setText("03:00");
        time3.setAlignmentX(0.5F);
        horariosPanel.add(time3);

        time4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time4.setText("04:00");
        time4.setAlignmentX(0.5F);
        horariosPanel.add(time4);

        time5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time5.setText("05:00");
        time5.setAlignmentX(0.5F);
        horariosPanel.add(time5);

        time6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time6.setText("06:00");
        time6.setAlignmentX(0.5F);
        horariosPanel.add(time6);

        time7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time7.setText("07:00");
        time7.setAlignmentX(0.5F);
        horariosPanel.add(time7);

        time8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time8.setText("08:00");
        time8.setAlignmentX(0.5F);
        horariosPanel.add(time8);

        time9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time9.setText("09:00");
        time9.setAlignmentX(0.5F);
        horariosPanel.add(time9);

        time10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time10.setText("10:00");
        time10.setAlignmentX(0.5F);
        horariosPanel.add(time10);

        time11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time11.setText("11:00");
        time11.setAlignmentX(0.5F);
        horariosPanel.add(time11);

        time12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time12.setText("12:00");
        time12.setAlignmentX(0.5F);
        horariosPanel.add(time12);

        time13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time13.setText("13:00");
        time13.setAlignmentX(0.5F);
        horariosPanel.add(time13);

        time14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time14.setText("14:00");
        time14.setAlignmentX(0.5F);
        horariosPanel.add(time14);

        time15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time15.setText("15:00");
        time15.setAlignmentX(0.5F);
        horariosPanel.add(time15);

        time16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time16.setText("16:00");
        time16.setAlignmentX(0.5F);
        horariosPanel.add(time16);

        time17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time17.setText("17:00");
        time17.setAlignmentX(0.5F);
        horariosPanel.add(time17);

        time18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time18.setText("18:00");
        time18.setAlignmentX(0.5F);
        horariosPanel.add(time18);

        time19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time19.setText("19:00");
        time19.setAlignmentX(0.5F);
        horariosPanel.add(time19);

        time20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time20.setText("20:00");
        time20.setAlignmentX(0.5F);
        horariosPanel.add(time20);

        time21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time21.setText("21:00");
        time21.setAlignmentX(0.5F);
        horariosPanel.add(time21);

        time22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time22.setText("22:00");
        time22.setAlignmentX(0.5F);
        horariosPanel.add(time22);

        time23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time23.setText("23:00");
        time23.setAlignmentX(0.5F);
        horariosPanel.add(time23);

        time24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time24.setText("24:00");
        time24.setAlignmentX(0.5F);
        horariosPanel.add(time24);

        diasSemana1.add(horariosPanel);

        domingoPanel.setMinimumSize(null);
        domingoPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        domingoPanel.setLayout(new javax.swing.BoxLayout(domingoPanel, javax.swing.BoxLayout.PAGE_AXIS));
        diasSemana1.add(domingoPanel);

        segundaPanel.setMinimumSize(null);
        segundaPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        segundaPanel.setLayout(new javax.swing.BoxLayout(segundaPanel, javax.swing.BoxLayout.PAGE_AXIS));
        diasSemana1.add(segundaPanel);

        tercaPanel.setMinimumSize(null);
        tercaPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        tercaPanel.setLayout(new javax.swing.BoxLayout(tercaPanel, javax.swing.BoxLayout.PAGE_AXIS));
        diasSemana1.add(tercaPanel);

        quartaPanel.setMinimumSize(null);
        quartaPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        quartaPanel.setLayout(new javax.swing.BoxLayout(quartaPanel, javax.swing.BoxLayout.PAGE_AXIS));
        diasSemana1.add(quartaPanel);

        quintaPanel.setMinimumSize(null);
        quintaPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        quintaPanel.setLayout(new javax.swing.BoxLayout(quintaPanel, javax.swing.BoxLayout.PAGE_AXIS));
        diasSemana1.add(quintaPanel);

        sextaPanel.setMinimumSize(null);
        sextaPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        sextaPanel.setLayout(new javax.swing.BoxLayout(sextaPanel, javax.swing.BoxLayout.PAGE_AXIS));
        diasSemana1.add(sextaPanel);

        sabadoPanel.setMinimumSize(null);
        sabadoPanel.setPreferredSize(new java.awt.Dimension(100, 447));
        sabadoPanel.setLayout(new javax.swing.BoxLayout(sabadoPanel, javax.swing.BoxLayout.PAGE_AXIS));
        diasSemana1.add(sabadoPanel);

        rotinaPanel.add(diasSemana1, java.awt.BorderLayout.CENTER);

        rotinaScroll.setViewportView(rotinaPanel);

        getContentPane().add(rotinaScroll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarioRotinaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarioRotinaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarioRotinaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarioRotinaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarioRotinaNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel diasSemana;
    private javax.swing.JPanel diasSemana1;
    private javax.swing.JPanel domingoPanel;
    private javax.swing.JLabel domingoTitulo;
    private javax.swing.JPanel horariosPanel;
    private javax.swing.JLabel horariosTitulo;
    private javax.swing.JPanel quartaPanel;
    private javax.swing.JLabel quartaTitulo;
    private javax.swing.JPanel quintaPanel;
    private javax.swing.JLabel quintaTitulo;
    private javax.swing.JPanel rotinaPanel;
    private javax.swing.JScrollPane rotinaScroll;
    private javax.swing.JPanel sabadoPanel;
    private javax.swing.JLabel sabadoTitulo;
    private javax.swing.JPanel segundaPanel;
    private javax.swing.JLabel segundaTitulo;
    private javax.swing.JPanel sextaPanel;
    private javax.swing.JLabel sextaTitulo;
    private javax.swing.JPanel tercaPanel;
    private javax.swing.JLabel tercaTitulo;
    private javax.swing.JLabel time0;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time10;
    private javax.swing.JLabel time11;
    private javax.swing.JLabel time12;
    private javax.swing.JLabel time13;
    private javax.swing.JLabel time14;
    private javax.swing.JLabel time15;
    private javax.swing.JLabel time16;
    private javax.swing.JLabel time17;
    private javax.swing.JLabel time18;
    private javax.swing.JLabel time19;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time20;
    private javax.swing.JLabel time21;
    private javax.swing.JLabel time22;
    private javax.swing.JLabel time23;
    private javax.swing.JLabel time24;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    private javax.swing.JLabel time6;
    private javax.swing.JLabel time7;
    private javax.swing.JLabel time8;
    private javax.swing.JLabel time9;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
