/*
 * Copyright (C) 2019 guscc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gato;

import java.awt.Color;
import java.awt.Label;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

/**
 *
 * @author guscc
 */


public class CalendarioCabub extends javax.swing.JFrame {
    
    /**
     * Creates new form CalendarioCabub
     */
    public CalendarioCabub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dias = new javax.swing.JPanel();
        dia1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        DiasSemana = new javax.swing.JPanel();
        Domingo = new javax.swing.JLabel();
        Segunda = new javax.swing.JLabel();
        Terça = new javax.swing.JLabel();
        Quarta = new javax.swing.JLabel();
        Quinta = new javax.swing.JLabel();
        Sexta = new javax.swing.JLabel();
        Sábado = new javax.swing.JLabel();
        TextoMes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dias.setLayout(new java.awt.GridLayout(6, 7));

        dia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dia1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dia1Layout = new javax.swing.GroupLayout(dia1);
        dia1.setLayout(dia1Layout);
        dia1Layout.setHorizontalGroup(
            dia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        dia1Layout.setVerticalGroup(
            dia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        Dias.add(dia1);

        getContentPane().add(Dias, java.awt.BorderLayout.CENTER);

        Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Titulo.setLayout(new java.awt.BorderLayout());

        DiasSemana.setBackground(new java.awt.Color(150, 150, 150));
        DiasSemana.setLayout(new java.awt.GridLayout(1, 0));

        Domingo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Domingo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Domingo.setText("Domingo");
        Domingo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Domingo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DiasSemana.add(Domingo);

        Segunda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Segunda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Segunda.setText("Segunda");
        Segunda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Segunda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DiasSemana.add(Segunda);

        Terça.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Terça.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Terça.setText("Terça");
        Terça.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Terça.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DiasSemana.add(Terça);

        Quarta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Quarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quarta.setText("Quinta");
        Quarta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Quarta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DiasSemana.add(Quarta);

        Quinta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Quinta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quinta.setText("Quarta");
        Quinta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Quinta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DiasSemana.add(Quinta);

        Sexta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sexta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sexta.setText("Sexta");
        Sexta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Sexta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DiasSemana.add(Sexta);

        Sábado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sábado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sábado.setText("Sábado");
        Sábado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Sábado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DiasSemana.add(Sábado);

        Titulo.add(DiasSemana, java.awt.BorderLayout.SOUTH);

        TextoMes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TextoMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoMes.setText("Mes");
        Titulo.add(TextoMes, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton1.setText(" ← ");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Titulo.add(jButton1, java.awt.BorderLayout.WEST);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton2.setText(" → ");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Titulo.add(jButton2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Titulo, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dia1MouseClicked
        Integer i = 1;
        new ListarDia(i).setVisible(true);
    }//GEN-LAST:event_dia1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarioCabub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarioCabub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarioCabub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarioCabub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarioCabub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dias;
    private javax.swing.JPanel DiasSemana;
    private javax.swing.JLabel Domingo;
    private javax.swing.JLabel Quarta;
    private javax.swing.JLabel Quinta;
    private javax.swing.JLabel Segunda;
    private javax.swing.JLabel Sexta;
    private javax.swing.JLabel Sábado;
    private javax.swing.JLabel Terça;
    private javax.swing.JLabel TextoMes;
    private javax.swing.JPanel Titulo;
    private javax.swing.JPanel dia1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
