package gato;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author drakcamicazi
 */
public class DeletarSemanal extends javax.swing.JFrame {

    public DeletarSemanal() {
        initComponents();
        popularEventos();
    }

    private void deletar(int cod) {
        int n = JOptionPane.showConfirmDialog(null, "Deseja mesmo deletar o evento " + cod + "?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (n == YES_OPTION) {
            String url = "jdbc:mysql://localhost/gato?useSSL=false", usuario = "root", senha = "root";
            Connection conexao;
            PreparedStatement pstm;
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DeletarSemanal.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                conexao = DriverManager.getConnection(url, usuario, senha);
                pstm = conexao.prepareStatement("delete from Evento_Semanal where pk_evento_semanal = ?");

                pstm.setInt(1, cod);

                pstm.execute();
                pstm.close();
                conexao.close();

                JOptionPane.showMessageDialog(null, "Evento " + cod + " deletado com sucesso!");
            } catch (HeadlessException | SQLException excp) {
                JOptionPane.showMessageDialog(null, "Erro ao deletar.");
                System.err.println(excp);
            }

            DeletarSemanal.this.dispose();
            DeletarSemanal ds = new DeletarSemanal();
            ds.setVisible(true);
        }
    }

    private void popularEventos() {
        String url = "jdbc:mysql://localhost/gato?useSSL=false", usuario = "root", senha = "root";
        Connection conexao;
        Statement stm;
        ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeletarSemanal.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            conexao = DriverManager.getConnection(url, usuario, senha);
            stm = conexao.createStatement();
            rs = stm.executeQuery("select pk_evento_semanal, titulo, dia_semana, hora_inicio, hora_fim from evento_semanal order by dia_semana asc, hora_inicio asc");

            while (rs.next()) {
                int cod = rs.getInt("pk_evento_semanal");
                JLabel l = new JLabel(cod + "- " + rs.getString("titulo") + ": " + rs.getString("dia_semana") + ", " + rs.getString("hora_inicio") +" - "+ rs.getString("hora_fim"));
                l.setFont(l.getFont().deriveFont(18.0f));
                l.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        deletar(cod);
                    }
                });
                pnListaEventos.add(l);
            }
            stm.close();
            conexao.close();
        } catch (HeadlessException | SQLException excp) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar do banco.");
            System.err.println(excp);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnListaEventos = new javax.swing.JPanel();
        lbInfo = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane(pnListaEventos);
        pnListaEventos.setSize(scroll.getWidth(), scroll.getHeight());

        pnListaEventos.setLayout(new BoxLayout(pnListaEventos,  javax.swing.BoxLayout.PAGE_AXIS));


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deletar Evento Semanal");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.BorderLayout(40, 10));

        lbInfo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfo.setText("Clique em um evento semanal para deletar:");
        getContentPane().add(lbInfo, java.awt.BorderLayout.PAGE_START);

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btFechar, java.awt.BorderLayout.PAGE_END);

        scroll.setMinimumSize(new java.awt.Dimension(500, 700));
        getContentPane().add(scroll, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("Deletar Evento Semanal");

        pack();
    }// </editor-fold>                          

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {
        DeletarSemanal.this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletarSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletarSemanal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JPanel pnListaEventos;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration                   
}
