/*
 * Copyright (C) 2019 guscc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gato;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author guscc
 */
public class ListasExpandidas extends javax.swing.JFrame {

    /**
     * Creates new form ListasExpandidas
     */
    public ListasExpandidas() {
        this.setExtendedState(this.getExtendedState() | ListasExpandidas.MAXIMIZED_BOTH);
        initComponents();
        preencherListas();
    }
    
    private void preencherListas()
    {
        String url = "jdbc:mysql://localhost/gato?useSSL=false", usuario = "root", senha = "root";
        Connection conexao;
        PreparedStatement pstm;
        ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeletarSemanal.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            conexao = DriverManager.getConnection(url, usuario, senha);
            pstm = conexao.prepareStatement("select titulo, dia, hora_inicio, hora_fim, descricao from evento where dia > DATE(NOW()) and favorito = 1 order by dia asc, hora_inicio asc");

            pstm.execute();
            rs = pstm.getResultSet();

            while (rs.next()) {
                JLabel l1 = new JLabel(rs.getDate("dia").toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/uuuu")) +": "+ rs.getString("titulo") + ", das " +rs.getString("hora_inicio") + " às " + rs.getString("hora_fim"));
                l1.setFont(l1.getFont().deriveFont(18.0f));
                JLabel l2 = new JLabel("    "+rs.getString("descricao"));
                l2.setFont(l2.getFont().deriveFont(14.0f));
                
                listaEventosFav.add(l1);
                listaEventosFav.add(l2);
            }
            pstm.close();
            
            pstm = conexao.prepareStatement("select titulo, dia, hora_inicio, hora_fim, descricao from evento where dia > DATE(NOW()) and atividade = 1 order by dia asc, hora_inicio asc");

            pstm.execute();
            rs = pstm.getResultSet();

            while (rs.next()) {
                JLabel l1 = new JLabel(rs.getDate("dia").toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/uuuu")) +": "+ rs.getString("titulo") + ", das " +rs.getString("hora_inicio") + " às " + rs.getString("hora_fim"));
                l1.setFont(l1.getFont().deriveFont(18.0f));
                JLabel l2 = new JLabel("    "+rs.getString("descricao"));
                l2.setFont(l2.getFont().deriveFont(14.0f));
                
                listaEventosAtiv.add(l1);
                listaEventosAtiv.add(l2);
            }
            pstm.close();
            
            
            
            conexao.close();
        } catch (HeadlessException | SQLException excp) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar do banco.");
            System.err.println(excp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTabelas = new javax.swing.JPanel();
        tabelaFavorito = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        scrollEventos = new javax.swing.JScrollPane();
        listaEventosFav = new javax.swing.JPanel();
        tabelaAtividades = new javax.swing.JPanel();
        scrollEventos2 = new javax.swing.JScrollPane();
        listaEventosAtiv = new javax.swing.JPanel();
        panelTitulo2 = new javax.swing.JPanel();
        textTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Favoritos e Atividades");
        setPreferredSize(new java.awt.Dimension(1200, 600));

        painelTabelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelTabelas.setMinimumSize(new java.awt.Dimension(150, 150));
        painelTabelas.setPreferredSize(new java.awt.Dimension(150, 150));
        painelTabelas.setLayout(new java.awt.GridLayout(1, 0));

        tabelaFavorito.setPreferredSize(new java.awt.Dimension(150, 264));
        tabelaFavorito.setLayout(new java.awt.BorderLayout());

        panelTitulo.setLayout(new java.awt.BorderLayout());

        textTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("Favoritos");
        textTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(textTitulo, java.awt.BorderLayout.CENTER);

        tabelaFavorito.add(panelTitulo, java.awt.BorderLayout.NORTH);

        scrollEventos.setMinimumSize(new java.awt.Dimension(150, 350));
        scrollEventos.setPreferredSize(new java.awt.Dimension(150, 350));

        listaEventosFav.setMaximumSize(new java.awt.Dimension(10000, 10000));
        listaEventosFav.setMinimumSize(new java.awt.Dimension(100, 100));
        listaEventosFav.setPreferredSize(new java.awt.Dimension(150, 800));
        listaEventosFav.setLayout(new javax.swing.BoxLayout(listaEventosFav, javax.swing.BoxLayout.PAGE_AXIS));
        scrollEventos.setViewportView(listaEventosFav);

        tabelaFavorito.add(scrollEventos, java.awt.BorderLayout.CENTER);

        painelTabelas.add(tabelaFavorito);

        tabelaAtividades.setMinimumSize(new java.awt.Dimension(150, 394));
        tabelaAtividades.setLayout(new java.awt.BorderLayout());

        scrollEventos2.setMinimumSize(new java.awt.Dimension(150, 350));
        scrollEventos2.setPreferredSize(new java.awt.Dimension(150, 350));

        listaEventosAtiv.setMaximumSize(new java.awt.Dimension(10000, 10000));
        listaEventosAtiv.setMinimumSize(new java.awt.Dimension(100, 100));
        listaEventosAtiv.setPreferredSize(new java.awt.Dimension(150, 800));
        listaEventosAtiv.setLayout(new javax.swing.BoxLayout(listaEventosAtiv, javax.swing.BoxLayout.PAGE_AXIS));
        scrollEventos2.setViewportView(listaEventosAtiv);

        tabelaAtividades.add(scrollEventos2, java.awt.BorderLayout.CENTER);

        panelTitulo2.setLayout(new java.awt.BorderLayout());

        textTitulo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo2.setText("Atividades");
        textTitulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo2.add(textTitulo2, java.awt.BorderLayout.CENTER);

        tabelaAtividades.add(panelTitulo2, java.awt.BorderLayout.NORTH);

        painelTabelas.add(tabelaAtividades);

        getContentPane().add(painelTabelas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListasExpandidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListasExpandidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListasExpandidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListasExpandidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListasExpandidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel listaEventosAtiv;
    private javax.swing.JPanel listaEventosFav;
    private javax.swing.JPanel painelTabelas;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTitulo2;
    private javax.swing.JScrollPane scrollEventos;
    private javax.swing.JScrollPane scrollEventos2;
    private javax.swing.JPanel tabelaAtividades;
    private javax.swing.JPanel tabelaFavorito;
    private javax.swing.JLabel textTitulo;
    private javax.swing.JLabel textTitulo2;
    // End of variables declaration//GEN-END:variables
}
